// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/auth/generate-authentication.ts";
import * as $1 from "./routes/auth/generate-registration.ts";
import * as $2 from "./routes/auth/verify-authentication.ts";
import * as $3 from "./routes/auth/verify-registration.ts";
import * as $4 from "./routes/index.tsx";
import * as $5 from "./routes/login.tsx";
import * as $6 from "./routes/signup.tsx";
import * as $$0 from "./islands/LogInForm.tsx";
import * as $$1 from "./islands/SignUpForm.tsx";

const manifest = {
  routes: {
    "./routes/auth/generate-authentication.ts": $0,
    "./routes/auth/generate-registration.ts": $1,
    "./routes/auth/verify-authentication.ts": $2,
    "./routes/auth/verify-registration.ts": $3,
    "./routes/index.tsx": $4,
    "./routes/login.tsx": $5,
    "./routes/signup.tsx": $6,
  },
  islands: {
    "./islands/LogInForm.tsx": $$0,
    "./islands/SignUpForm.tsx": $$1,
  },
  baseUrl: import.meta.url,
};

export default manifest;
